# Generated by Django 4.2.6 on 2023-10-31 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0002_alter_comment_table_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
